-- ============================================
-- 새로 추가된 컬럼 확인 쿼리
-- ============================================

-- 1. LESSONS 테이블에 CATEGORY 컬럼 확인
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'LESSONS' AND COLUMN_NAME = 'CATEGORY';

-- 2. TRAINING_LOGS 테이블에 TRAINING_PART 컬럼 확인
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TRAINING_LOGS' AND COLUMN_NAME = 'TRAINING_PART';

-- 3. BOOKINGS 테이블에 LESSON_CATEGORY 컬럼 확인
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BOOKINGS' AND COLUMN_NAME = 'LESSON_CATEGORY';

-- 4. 전체 컬럼 구조 확인
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME IN ('LESSONS', 'TRAINING_LOGS', 'BOOKINGS')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
